### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by abraxxa** [netdisco/snmp-info#255]
## Expected Behavior
Passing a fqdn with a AAAA record uses its IPv6 address, passing an IPv6 address works too.

## Current Behavior
When passing a fqdn to DestHost, which only has a AAAA DNS record, SNMP::Info fails with:
`getaddrinfo: hostname.example.org Name or service not known`

When passing an IPv6 address to DestHost with Debug enabled SNMP::Info fails with:
`error:snmp_new_session: Couldn't open SNMP session at /home/username/perl5/perlbrew/perls/5.22.1/lib/site_perl/5.22.1/x86_64-linux/SNMP.pm line 520.`

## Workaround
@ollyg suggested on IRC the workaround of specifying the IPv6 address in the format 'udp6:[$ipv6]' which indeed works.

## Possible Solution
1. Fix the DNS resolution to also use AAAA records.
2. automatically pass the IPv6 address in the format udp6:[$ipv6] to SNMP::Session so that its (undocumented) interface doesn't propagate to SNMP::Infos.

## Your Environment
* SNMP::Info version used: 3.36

**Comment by jeneric** [comment]
Currently we don't do any validation on the 'DestHost' parameter of the constructor, just handing it off to Net-SNMP which uses a scheme of '[transport-specifier:]transport-address' as documented in the [snmpd man page](http://www.net-snmp.org/docs/man/snmpd.html).

Although I'm hesitant about pulling dependencies into the library, I think we would probably be best served by using Regex:Common to validate and identify the address type since there are so many variations of IPv6 addresses.

As far as the AAAA DNS record, I think it's failing today because it would need to be prefixed with the udp6 transport as well. Since there is no way to know if the fqdn is IPv6 or IPv4 I think we will first have to resolve the address to determine if it requires the 'udp6' transport. This will add DNS resolution code that we previously haven't had to deal with in SNMP::Info unless there is a better idea. It also might be best served by another library / dependency since the resolver code may be dependent upon the platform we are running on.

**Comment by ollyg** [comment]
Both [Regexp::Common](https://metacpan.org/pod/Regexp::Common) and [NetAddr::IP](https://metacpan.org/pod/NetAddr::IP) could do the job, and both have "no dependencies" as far as I can tell.

The advantage of NetAddr::IP is that we can pass _almost anything_ into the constructor, extract the IP, and then ask how many bits the resultant address has (to determine whether to prefix with `udp:`). I believe if given an FQDN with both A and AAAA, the A will be preferred.
