### ISSUE TITLE
Add support for Mellanox 

### ISSUE THREAD

**Issue by SharonYeuda** [netdisco/snmp-info#311]
## Expected Behavior
Getting all VLANs names, interface descriptions,MAC address table,LLDP neighbors . 
Also, Vendor/Model and Device MAC address at the details page.

## Possible Solution
Please check: **Getting Started with SNMP MIBs for Mellanox Switches**
[https://community.mellanox.com/s/article/getting-started-with-snmp-mibs-for-mellanox-switches](url)
OIDs:
1.3.6.1.2.1.17.1.1 - Switch MAC address
1.3.6.1.2.1.17.7.1.2.2 - MAC address table
1.3.6.1.2.1.17.7.1.4.3.1.1 - VLANs names
1.3.6.1.2.1.47.1.1.1.1.11.1 - Serial Number
1.3.6.1.2.1.31.1.1.1.18 - ifAlias
1.0.8802.1.1.2.1.4.1.1.9 - LLDP
![mellanox net disco interfaces page](https://user-images.githubusercontent.com/10217743/53325307-b5330300-38eb-11e9-841b-5bb7a1904393.PNG)

![mellanox net disco details page](https://user-images.githubusercontent.com/10217743/53324360-45bc1400-38e9-11e9-817b-a9e70de65370.PNG)

## Your Device

* Vendor: Mellanox
* Device Model:MSN2410
* Operating System Version:SWv3.6.6102
* Snmpwalk output of .1.3.6.1.2.1.1:
.1.3.6.1.2.1.1.1.0 "Onyx,MSN2410,SWv3.6.6102"
.1.3.6.1.2.1.1.2.0 .1.3.6.1.4.1.33049.1.1.1.2410
.1.3.6.1.2.1.1.3.0 288:6:25:54.41
.1.3.6.1.2.1.1.4.0 "unknown"
.1.3.6.1.2.1.1.5.0 "MellanoxSW01"
.1.3.6.1.2.1.1.6.0 "Room-C"
.1.3.6.1.2.1.1.7.0 72
.1.3.6.1.2.1.1.8.0 0:0:00:00.07
.1.3.6.1.2.1.1.9.1.2.1 .1.3.6.1.6.3.11.2.3.1.1
.1.3.6.1.2.1.1.9.1.2.2 .1.3.6.1.6.3.15.2.1.1
.1.3.6.1.2.1.1.9.1.2.3 .1.3.6.1.6.3.10.3.1.1
.1.3.6.1.2.1.1.9.1.2.4 .1.3.6.1.6.3.1
.1.3.6.1.2.1.1.9.1.2.5 .1.3.6.1.2.1.49
.1.3.6.1.2.1.1.9.1.2.6 .1.3.6.1.2.1.4
.1.3.6.1.2.1.1.9.1.2.7 .1.3.6.1.2.1.50
.1.3.6.1.2.1.1.9.1.2.8 .1.3.6.1.6.3.16.2.2.1
.1.3.6.1.2.1.1.9.1.3.1 "The MIB for Message Processing and Dispatching."
.1.3.6.1.2.1.1.9.1.3.2 "The MIB for Message Processing and Dispatching."
.1.3.6.1.2.1.1.9.1.3.3 "The SNMP Management Architecture MIB."
.1.3.6.1.2.1.1.9.1.3.4 "The MIB module for SNMPv2 entities"
.1.3.6.1.2.1.1.9.1.3.5 "The MIB module for managing TCP implementations"
.1.3.6.1.2.1.1.9.1.3.6 "The MIB module for managing IP and ICMP implementations"
.1.3.6.1.2.1.1.9.1.3.7 "The MIB module for managing UDP implementations"
.1.3.6.1.2.1.1.9.1.3.8 "View-based Access Control Model for SNMP."
.1.3.6.1.2.1.1.9.1.4.1 0:0:00:00.07
.1.3.6.1.2.1.1.9.1.4.2 0:0:00:00.07
.1.3.6.1.2.1.1.9.1.4.3 0:0:00:00.07
.1.3.6.1.2.1.1.9.1.4.4 0:0:00:00.07
.1.3.6.1.2.1.1.9.1.4.5 0:0:00:00.07
.1.3.6.1.2.1.1.9.1.4.6 0:0:00:00.07
.1.3.6.1.2.1.1.9.1.4.7 0:0:00:00.07
.1.3.6.1.2.1.1.9.1.4.8 0:0:00:00.07

## Your Environment

* SNMP::Info version used: 3.64
* Netdisco version (if used): 2.40.2

**Comment by inphobia** [comment]
so it seems this device is reporting it supports layers 4 & 7, and since snmp::info does not have a specific class for these yet it will just go on whatever data the device provides.

snmp::info is using it's generic layer7 module for this and all the info you expect won't be collected when using layer7.

that was the bad news, now the good.

since they claim to support most standard mibs, and assuming they don't have any strange quircks, basic support for the device shouldn't be hard to add.

while i haven't yet tried this myself i think an easy way would be to overwrite this in the main snmp::info module:
https://github.com/netdisco/snmp-info/blob/master/lib/SNMP/Info.pm#L2066 , perhaps by adding something like this:

```
$objtype = 'SNMP::Info::Layer3'
if ( $soid =~ /\.1\.3\.6\.1\.4\.1\.33049/i );
```

this will make it use snmp::info::layer3 instead, which in turn will pull in most of the other modules needed to get the data you expect (snmp::info::layer2 could be an alternative, really depends on what modules they in turn include).

if this does not work out of the box then a specific device module will be needed.

for this there are 2 options:
- write the support yourself
- provide snmpdata and wait for a snmp::info dev to have some spare time

more info can be found here: https://metacpan.org/pod/SNMP::Info#EXTENDING-SNMP::INFO 


##### writing a module yourself
while this sounds complicated it's quite doable if the device does not have to many strange quircks. basic support (using some vendor mib data, overwriting a select few things) can be done even if you are not a perl guru. an example of very basic support can be found here: https://github.com/inphobia/snmp-info/blob/2b73601a4cd0eef7ee2cd8ade5f65a1bde92423d/lib/SNMP/Info/Layer3/Lenovo.pm

we are more than happy to accept any code you write and help you get started (either via the snmp info mailing list, irc or ticket updates).

##### providing the required data for us to add support
for this we could really use the snmpdata from the device, preferably in snmprec format. the procedure for this can be found here: https://github.com/netdisco/snmp-info/wiki/Simulating-Agents#2-get-snmp-datadump

then the waiting game starts, as much as we'd want to add support for a device we also need to find the time to write the code. i'm more then willing to add this to my queue, but right now i'm trying to get lenovo support done first. a realistic estimate would be 3-4 weeks i think.

**Comment by SharonYeuda** [comment]
Hi, 

I think I'd rather you the pros add the device : )
Addteched a Dump file of Mellanox 2400 model.

Thanks in advance

[MLNX-2400.txt](https://github.com/netdisco/snmp-info/files/3657834/MLNX-2400.txt)

**Comment by inphobia** [comment]
i can put it on my todo list, but if possible an snmprec file instead of snmpwalk would be welcome. the conversion process of snmpwalk -> snmprec so it can be loaded it snmpsim is prone to changing data in subtle ways.

a quick guide can be found here: https://github.com/netdisco/snmp-info/wiki/Simulating-Agents#21-snmpsim--snmprec-version

thx in advance.

**Comment by edo1** [comment]
@inphobia I have Mellanox switch as well
> while i haven't yet tried this myself i think an easy way would be to overwrite this in the main snmp::info module:
> https://github.com/netdisco/snmp-info/blob/master/lib/SNMP/Info.pm#L2066 , perhaps by adding something like this:

I tried to add 
```
        $objtype = 'SNMP::Info::Layer3'
            if ( $soid =~ /\.3\.6\.1\.4\.1\.33049/i );
```

On `Details` tab `SNMP Class` changes to `SNMP::Info::Layer3`
`Arpnip` and `Macsuck` buttons are unavailable.
![image](https://user-images.githubusercontent.com/221688/82381505-fd7b9b00-9a32-11ea-955b-befaa103446d.png)

On `Ports` tab VLAN information arrives, but there are still no MACs:
![image](https://user-images.githubusercontent.com/221688/82380954-0ddf4600-9a32-11ea-9a39-62b1495b6348.png)

What's next?

**Comment by SharonYeuda** [comment]
Hi, 
Is there any new with this?
I tried to do what edo1 did with no luck..

**Comment by SharonYeuda** [comment]
Hi,
Attached snmprec file for Mellanox 2700 switch (I have change it the to **txt**)

[mellanox_2700.txt](https://github.com/netdisco/snmp-info/files/5542185/mellanox_2700.txt)

Thanks

**Comment by SharonYeuda** [comment]
Hi, Any new?

**Comment by SharonYeuda** [comment]
Duplicate with 

https://github.com/netdisco/snmp-info/issues/396
