### ISSUE TITLE
Unable to collect mac addresses

### ISSUE THREAD

**Issue by lucap22** [netdisco/snmp-info#314]
Hello,
on a cisco nexus 3k netdisco fails to get mac addresses of some connected devices, it seems to work only with vlan tagged and a few untagged vlan, see screenshot attached
![screenshot_2019-03-07- ports 1](https://user-images.githubusercontent.com/48315695/53952993-92b29e00-40d2-11e9-933d-f702455e3660.png)

## Expected Behavior

get mac address for all ports

## Current Behavior

get mac address only for tagged vlan ed some untagged vlan

## Steps to Reproduce (for bugs)

1. 
```
netdisco-do psql -e "SELECT * FROM node WHERE switch='10.0.33.101' and port = 'Ethernet1/8' "
[48815] 2019-03-07 10:54:08  info App::Netdisco version 2.040006 loaded.
[48815] 2019-03-07 10:54:08  info psql:  started at Thu Mar  7 11:54:08 2019
 mac | switch | port | vlan | active | oui | time_first | time_recent | time_last 
-----+--------+------+------+--------+-----+------------+-------------+-----------
(0 rows)

[48815] 2019-03-07 10:54:08  info psql: finished at Thu Mar  7 11:54:08 2019
[48815] 2019-03-07 10:54:08  info psql: status done: psql session closed.
```

2. 
```
netdisco-do psql -e "select ip,port,vlan from device_port where ip = '10.0.33.101' and port = 'Ethernet1/8'" 
[647] 2019-03-07 10:54:33  info App::Netdisco version 2.040006 loaded.
[647] 2019-03-07 10:54:33  info psql:  started at Thu Mar  7 11:54:33 2019
     ip      |    port     | vlan 
-------------+-------------+------
 10.0.33.101 | Ethernet1/8 | 12
(1 row)

[647] 2019-03-07 10:54:33  info psql: finished at Thu Mar  7 11:54:33 2019
[647] 2019-03-07 10:54:33  info psql: status done: psql session closed.
```

3. 
```
~netdisco/bin/netdisco-do show -d 10.0.33.101 -e fw_mac
[25722] 2019-03-07 08:54:39  info App::Netdisco version 2.040006 loaded.
[25722] 2019-03-07 08:54:39  info show: [10.0.33.101]/fw_mac started at Thu Mar  7 09:54:39 2019
\ {
    .....
    12.128.24.68.225.78.32         "80:18:44:e1:4e:20",
    .....
}
[25722] 2019-03-07 08:54:40  info show: finished at Thu Mar  7 09:54:40 2019
[25722] 2019-03-07 08:54:40  info show: status done: Showed fw_mac response from 10.0.33.101
```

4. 
```
~netdisco/bin/netdisco-do show -d 10.0.33.101 -e fw_port
[45999] 2019-03-06 16:48:50  info App::Netdisco version 2.040006 loaded.
[45999] 2019-03-06 16:48:50  info show: [10.0.33.101]/fw_port started at Wed Mar  6 17:48:50 2019
\ {
    .....
    12.128.24.68.225.78.32         8,
    .....
}
[45999] 2019-03-06 16:48:51  info show: finished at Wed Mar  6 17:48:51 2019
[45999] 2019-03-06 16:48:51  info show: status done: Showed fw_port response from 10.0.33.101
```
5.
```
sh mac add int Eth1/8
   VLAN     MAC Address      Type      age     Secure NTFY Ports
---------+-----------------+--------+---------+------+----+------------------
*   12     8018.44e1.4e20   dynamic  0         F      F    Eth1/8
```

## Your Device

* Vendor: Cisco 
* Device Model: N3K-C3048TP-1GE
* Operating System Version:  NX-OS 7.0(3)I7(5a)
* Snmpwalk output of .1.3.6.1.2.1.1:
SNMPv2-MIB::sysDescr.0 = STRING: Cisco NX-OS(tm) nxos.7.0.3.I7.5a.bin, Software (nxos), Version 7.0(3)I7(5a), RELEASE SOFTWARE Copyright (c) 2002-2018 by Cisco Systems, Inc. Compiled 10/12/2018 18:00:00
SNMPv2-MIB::sysObjectID.0 = OID: SNMPv2-SMI::enterprises.9.12.3.1.3.1106
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (125142997) 14 days, 11:37:09.97
SNMPv2-MIB::sysContact.0 = STRING: 
SNMPv2-MIB::sysName.0 = STRING: xxxxxx
SNMPv2-MIB::sysLocation.0 = STRING: 
SNMPv2-MIB::sysServices.0 = INTEGER: 70
SNMPv2-MIB::sysORLastChange.0 = Timeticks: (2) 0:00:00.02
SNMPv2-MIB::sysORID.1 = OID: SNMPv2-MIB::snmpMIB
SNMPv2-MIB::sysORID.2 = OID: SNMP-VIEW-BASED-ACM-MIB::vacmBasicGroup
SNMPv2-MIB::sysORID.3 = OID: SNMP-FRAMEWORK-MIB::snmpFrameworkMIBCompliance
SNMPv2-MIB::sysORID.4 = OID: SNMP-MPD-MIB::snmpMPDCompliance
SNMPv2-MIB::sysORID.5 = OID: SNMP-USER-BASED-SM-MIB::usmMIBCompliance
SNMPv2-MIB::sysORDescr.1 = STRING: The MIB module for SNMPv2 entities
SNMPv2-MIB::sysORDescr.2 = STRING: View-based Access Control Model for SNMP.
SNMPv2-MIB::sysORDescr.3 = STRING: The SNMP Management Architecture MIB.
SNMPv2-MIB::sysORDescr.4 = STRING: The MIB for Message Processing and Dispatching.
SNMPv2-MIB::sysORDescr.5 = STRING: The management information definitions for the SNMP User-based Security Model.
SNMPv2-MIB::sysORUpTime.1 = Timeticks: (2) 0:00:00.02
SNMPv2-MIB::sysORUpTime.2 = Timeticks: (2) 0:00:00.02
SNMPv2-MIB::sysORUpTime.3 = Timeticks: (2) 0:00:00.02
SNMPv2-MIB::sysORUpTime.4 = Timeticks: (2) 0:00:00.02
SNMPv2-MIB::sysORUpTime.5 = Timeticks: (2) 0:00:00.02

## Your Environment

* SNMP::Info version used: 3.65
* Netdisco version (if used): App::Netdisco version 2.040006

**Comment by inphobia** [comment]
heya, a few questions:

1) are you running vrfs?
2) are you running a vpc config?
3) have you tried the sshcollector or just snmp?

thx

**Comment by lucap22** [comment]
Hello inphobia,
sorry for the delay in response,

1. are you running vrfs?
 - only defaults ( default, management )
2. are you running a vpc config?
- yes, this device is connected to a pair of Cisco Nexus with vPC configured
3. have you tried the sshcollector or just snmp?
- with snmp works fine but also with "nettdisco-do show" as shown above.

What do you suggest?

**Comment by inphobia** [comment]
late reply, but here goes:
are your vmware servers connected either:
   -  via a vpc
   - are you running cisco ucs blades


if either of those is true you're most likely seeing what's mentioned in netdisco/netdisco#514 and netdisco/netdisco#524 -> a node mac address can only be linked to 1 device port atm in the netdisco db.

when running a vpc setup however the node mac address willl show up on both devices since that's kinda the selling point of vpc and other virtual link aggr solutions. so netdisco will show the mac address on the device that was last discovered/macsucked.

for 1 of your devices, try to run the following 4 commands in succession:
```
netdisco-do discover -d 10.0.33.101
netdisco-do macsuck -d 10.0.33.101
netdisco-do psql -e "SELECT * FROM node WHERE switch='10.0.33.101' and port = 'Ethernet1/8' "
 -> also same netdisco-do psql but then with the ip & port of the second switch in your vpc config
```

this should have the result that now the node is registered on your first switch.

if you repeat discover & macsuck on the second switch in the vpc stack & then do both psql commands again, i expect the node will have moved.

can you report back?

thx

**Comment by lucap22** [comment]
Hello,

no vpc configured on vmware servers, they have multiple uplink managed by vmware Distributed Switch. On this device VPC is not configured, it's connected to two different Cisco Nexus where VPC is configured, so this device have only one port-channel as a uplink.
I made a test, I moved a port on a different VLAN and then netdisco has begun to collect mac address for this port, so I changed back the VLAN and netdisco has stopped to collect the mac address. L3 of the VLAN that doesn't work is managed, with HSRP, by the two Cisco Nexus where VPC is configured, whereas the L3 of VLAN that work is configured to a third device.

![Screenshot_2019-03-27 sw315 wan serverplan com - Ports](https://user-images.githubusercontent.com/48315695/55062754-e5023180-5076-11e9-8b1e-0fdb287150a9.png)

**Comment by inphobia** [comment]
late reply, but haven't forgotten about this.

i too have seen anomalies related to our vmware servers, but haven't yet found the time or priority to actually dive into it.

what kind of vmware servers do you have? i'm running cisco blades (b200 m5 series), with 2 6248 series fabric interconnect per chassis group. the fabric interconnects that go to nexus9332pq pairs on 7.0.3.I7.5a.

issues i'm having seem to be even worse.
on the vmware side (don't forget snmp::info::layer7::vmware exists). we use a mix of classis virtual switches (management,vcenter ha, nfs, ...) and distributed vswitches (all virtual machines) .
![image](https://user-images.githubusercontent.com/39005454/59558741-5c51bc80-8ff9-11e9-8e1d-72b527f84f46.png)
vmware has an extensive mib library but, at least to me, also a very complex one.  (improving s::i::layer7::vmware is somewhere low on my prio list)

next in the path are those fabric interconnects (those run nx-os).
here vmware servers are detected (we run lldp and cdp on the vmware blades) if they run cdp, lldp esx hosts are not reported. also need to figure out where those ids come from that are being reported, since they seem bogus at first glance:
![image](https://user-images.githubusercontent.com/39005454/59558805-f403da80-8ffa-11e9-9b50-b1ac4a770c0d.png)
no nodes reported. 


even further down the path are the nexus c9332pq switches. nodes are reported "sometimes", but our vpc setup is part of the problem there (netdisco will report clients on a vpc bundle on the last scanned device only. iirc dublicate mac<->port mappings are semi supported: only the most recent mapping however will be the "active" one, and only this will be shown)

i'll open issues for this so i remember to look at this when time permits.

anyway, enough rambling about my issues, now lets check yours.

the hsrp thing is quite important however, since netdisco has special handling for that. and that special handling is mostly to ignore hsrpv1/v2&vrrp virtual ips in most codepaths).

so, if i understand correctly.
* you have the vmware server(s) connected with 1 port to each 3048 nexus.
* on the nexus side you have a vpc config with the vmware server.
* you're using distributed vswitches on the vmware side
  * about those distributed vswitches:
    * what version of vmware are you running and what distri vswitch version are you using?
    * how are those vswitches configured, are they using lacp.
    * is cdp and/or lldp active on the vmware side?

also, are any of your virtual machines running cdp and/or lldp?

**Comment by lucap22** [comment]
Hello,

sorry for the late reply,
this issue seems to be not related to esxi hosts, netdisco can't even collect mac-address of physical hosts, neither Windows nor Linux.
I did a test, I have replaced NXOS with an older version 7.0.3.I7.3 instead of 7.0.3.I7.5a and netdisco started collecting mac-address. Then I repeated the process on other nexus with the same result.
At this point I don't know if is a netdisco issue.
Do you want make a test on your enviroment?

**Comment by inphobia** [comment]
> sorry for the late reply,

seems i also have that issue 😄 .
this is just an update to let you know we haven't forgotten you, but i'll need some time to review the data again. hope to get back on this in a few days.

**Comment by lucap22** [comment]
Hello inphobia,

I have updated netdisco and snmp-info to the last release and mac collecting started working again.

**Comment by inphobia** [comment]
excellent :)
