### ISSUE TITLE
Can't get at error from 

### ISSUE THREAD

**Issue by abraxxa** [netdisco/snmp-info#460]
## Expected Behavior
A failed object construction should throw an error.

## Current Behavior
The errors from SNMP::Session are swallowed because throw_error populates $self->error but doesn't throw an exception contrary to its name:
https://metacpan.org/dist/SNMP-Info/source/lib/SNMP/Info.pm#L1437
https://metacpan.org/dist/SNMP-Info/source/lib/SNMP/Info.pm#L1444

Because the object isn't returned in the line below, there is no way to access the error.

## Possible Solution
Throw an exception instead of just populating $self->error.

## Steps to Reproduce (for bugs)

1.  create a SNMP::Info object for a not reachable device
2. AutoSpecify might need to be enabled
3. Don't enable Debug as this would make throw_error carp

## Your Device

* Vendor: any
* Device Model: any
* Operating System Version: any
* Snmpwalk output of .1.3.6.1.2.1.1: -

## Your Environment

* SNMP::Info version used: 3.82
* Netdisco version (if used): -

**Comment by ollyg** [comment]
Thanks @abraxxa this is fixed in 9042ad75
While it still does not throw an error, it at least now always returns `$info` so you can get error

**Comment by abraxxa** [comment]
Why not throw an error like in line 79?

**Comment by ollyg** [comment]
@abraxxa hi, mainly because I wanted to keep the behaviour as close as possible to the original SYNOPSIS.

Yes the original SYNOPSIS was broken, but clearly the intention was to return $info and have user check error(). So I kept that behaviour.

Actually dying or croaking in SNMP::Info seems to be reserved for more systems errors, like failing to load a MIB or Perl module. So for errors in SNMP::Session creation or connection, then we do not seem to die. I believe that is also more consistent with SNMP agent behaviour where it will reply even if ACL or Auth is wrong.

**Comment by abraxxa** [comment]
I understand, thanks Oliver!
